plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - "bin/**/*"
    - "config/environments/**/*"
    - "db/cable_schema.rb"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "tmp/**/*"
    - "vendor/**/*"
