# Deploy to these servers.
servers:
  web:
    - 46.225.67.171
  # job:
  #   hosts:
  #     - 46.225.67.171
  #   cmd: bin/good_job start --enable-cron

proxy:
  ssl: true
  hosts:
    - linky.lavenda.com.br

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    ## Rails
    RAILS_ENV: production
    ## Database
    POSTGRES_HOST: 46.225.67.171
    POSTGRES_PORT: 5432
    POSTGRES_USER: linky
    POSTGRES_DB: linky_production

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "production_linky_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
  cache:
    type: registry
    options: mode=max
    image: owalmirneto/linky:latest

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: postgres:18.1
    hosts:
      - 46.225.67.171
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: linky
        POSTGRES_DB: linky_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql
